version: '3'
services:
  resumed_webhook:
    container_name: resumed-webhook
    image: resumed_api:latest
    ports:
      - '5500:5500'
    depends_on:
      - resumed_db
      - resumed_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@resumed_db:5432/resumed
    command: bash -c 'npm run webhook'
  resumed_studio:
    container_name: resumed-studio
    image: resumed_api:latest
    ports:
      - '5555:5555'
    depends_on:
      - resumed_db
      - resumed_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@resumed_db:5432/resumed
    command: bash -c 'npx prisma studio'
  resumed_db:
    container_name: resumed-db
    image: postgres:14
    command: -c ssl=off
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=resumed
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=resumed_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - '5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  resumed_api:
    container_name: resumed-server
    image: resumed_api:latest
    ports:
      - '4000:4000'
    depends_on:
      - resumed_db
    environment:
      DATABASE_URL: postgres://postgres:postgres@resumed_db:5432/resumed
    command:
      - bash
      - -c
      - |
        npx prisma generate
        npx prisma db push
        npm run start
networks:
  name: null
volumes:
  postgres-data:
