
name: Resumed API CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/loumonthjack/resumed-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate build ID
        id: prep
        run: |
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "::set-output name=BUILD_ID::dev-${sha}-${ts}" 
            else
              echo "::set-output name=BUILD_ID::stable-${sha}-${ts}" 
            fi
      - name: Echo ID
        run: |
            echo ${{ github.ref_name }}
            echo "${{ steps.prep.outputs.BUILD_ID }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Build action
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push image Backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.BUILD_ID }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile
      