name: Deploy Development API

on:
  workflow_run:
    workflows: ["Build API"]
    types:
      - completed
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/loumonthjack/resumed-api

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    environment: development
    steps:
    - name: Login to Github Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin 
    - name: Cleanup Docker Images
      run: sudo docker system prune --all --force
    - name: Pull Docker Image
      run: sudo docker pull ${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
    - name: Delete Old Container
      run: sudo docker rm -f resumed-api
    - name: Run New Container
      run: sudo docker run -d --name resumed-api -p 4000:4000 -e AWS_REGION=${{ secrets.AWS_REGION }} DATABASE_URL=${{ secrets.DATABASE_URL }} SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} SENDGRID_FROM_KEY=${{ secrets.SENDGRID_FROM_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} NODE_ENV=${{ vars.NODE_ENV }} ${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
    - name: Stall  20 seconds
      run: sleep 20
    - name: Check Container Status
      run: sudo docker ps -a
    - name: Check Container Logs
      run: sudo docker logs --detailed resumed-api
